// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiuo7wxrdd1HL0FPPrQGSSn-RQudItauw',
    appId: '1:1090898793151:android:8f7c4a184c06b4d1a76c0a',
    messagingSenderId: '1090898793151',
    projectId: 'fit-together-74181',
    databaseURL: 'https://fit-together-74181-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fit-together-74181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChOHXBpRCfgVdfk8OqORk1Mu_WMw_HEjw',
    appId: '1:1090898793151:ios:89894229a5fd7f1ea76c0a',
    messagingSenderId: '1090898793151',
    projectId: 'fit-together-74181',
    databaseURL: 'https://fit-together-74181-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fit-together-74181.appspot.com',
    iosClientId: '1090898793151-t422mgufogcjrfr260g42b0u8l4oja2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsApp',
  );
}
